-- Check BOM/BuildMyProduct table structure
SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME LIKE '%BOM%' OR TABLE_NAME LIKE '%Build%' OR TABLE_NAME LIKE '%Recipe%'
ORDER BY TABLE_NAME;

-- Check columns for BOM-related tables
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME IN ('BillOfMaterials', 'BillOfMaterialsLines', 'BomTaskStatus', 'BuildMyProduct')
ORDER BY TABLE_NAME, ORDINAL_POSITION;

-- Check Users/Manufacturers table
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'Users'
ORDER BY ORDINAL_POSITION;
