-- Check the actual schema of PurchaseOrderLines table
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE,
    COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'PurchaseOrderLines'
ORDER BY ORDINAL_POSITION;
