-- Check actual column names in Demo_Retail tables
SELECT 'Demo_Retail_Variant' AS TableName, COLUMN_NAME, DATA_TYPE 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'Demo_Retail_Variant'
ORDER BY ORDINAL_POSITION;

SELECT 'Demo_Retail_Price' AS TableName, COLUMN_NAME, DATA_TYPE 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'Demo_Retail_Price'
ORDER BY ORDINAL_POSITION;

SELECT 'Demo_Retail_Stock' AS TableName, COLUMN_NAME, DATA_TYPE 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'Demo_Retail_Stock'
ORDER BY ORDINAL_POSITION;
