-- Find the master product table
SELECT TABLE_NAME 
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_TYPE = 'BASE TABLE' 
    AND TABLE_NAME LIKE '%Product%'
    AND TABLE_NAME NOT LIKE 'Demo_%'
ORDER BY TABLE_NAME;
