-- Check what sales/transaction tables actually exist
SELECT TABLE_NAME 
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_NAME LIKE '%Sales%' 
   OR TABLE_NAME LIKE '%Transaction%'
   OR TABLE_NAME LIKE '%Demo%'
ORDER BY TABLE_NAME;

-- Check Demo_Sales structure
SELECT COLUMN_NAME, DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'Demo_Sales'
ORDER BY ORDINAL_POSITION;

-- Check if there's a details table
SELECT TABLE_NAME 
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_NAME LIKE '%Detail%' 
   OR TABLE_NAME LIKE '%Item%'
   OR TABLE_NAME LIKE '%Line%'
ORDER BY TABLE_NAME;
