-- Find all invoice/sales related tables
SELECT TABLE_NAME 
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_NAME LIKE '%Invoice%' 
   OR TABLE_NAME LIKE '%Sale%'
   OR TABLE_NAME LIKE '%Receipt%'
ORDER BY TABLE_NAME;

-- Check Sales table structure (had 18 records)
SELECT COLUMN_NAME, DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'Sales'
ORDER BY ORDINAL_POSITION;

-- Check if there's a SalesLines or InvoiceLines table
SELECT TABLE_NAME 
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_NAME LIKE '%Line%'
ORDER BY TABLE_NAME;
