-- Check GeneralLedger table schema to find correct column names
SELECT 
    COLUMN_NAME, 
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'GeneralLedger'
ORDER BY ORDINAL_POSITION;
