-- Check ManufacturingStock table structure
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ManufacturingStock'
ORDER BY ORDINAL_POSITION

-- Check StockroomStock table structure
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'StockroomStock'
ORDER BY ORDINAL_POSITION

-- Check Products table structure
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'Products'
WHERE COLUMN_NAME LIKE '%Name%'
ORDER BY ORDINAL_POSITION
