-- Check actual column names in the tables

PRINT '=== Demo_Retail_Product Columns ==='
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'Demo_Retail_Product'
ORDER BY ORDINAL_POSITION

PRINT ''
PRINT '=== Demo_Retail_Stock Columns ==='
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'Demo_Retail_Stock'
ORDER BY ORDINAL_POSITION

PRINT ''
PRINT '=== Demo_Retail_Variant Columns ==='
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'Demo_Retail_Variant'
ORDER BY ORDINAL_POSITION

PRINT ''
PRINT '=== Demo_Retail_Price Columns ==='
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'Demo_Retail_Price'
ORDER BY ORDINAL_POSITION
