-- Check columns in backup tables
SELECT 'SupplierInvoices_FINAL_BACKUP' AS TableName, COLUMN_NAME, DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'SupplierInvoices_FINAL_BACKUP'
ORDER BY ORDINAL_POSITION;

SELECT 'SupplierInvoiceLines_FINAL_BACKUP' AS TableName, COLUMN_NAME, DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'SupplierInvoiceLines_FINAL_BACKUP'
ORDER BY ORDINAL_POSITION;
