-- Check AP_Invoices table structure
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE,
    COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'AP_Invoices'
ORDER BY ORDINAL_POSITION;

-- Check if the columns in the error exist
SELECT 
    CASE WHEN EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AP_Invoices' AND COLUMN_NAME = 'Reference') THEN 'YES' ELSE 'NO' END AS HasReference,
    CASE WHEN EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AP_Invoices' AND COLUMN_NAME = 'Debit') THEN 'YES' ELSE 'NO' END AS HasDebit,
    CASE WHEN EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AP_Invoices' AND COLUMN_NAME = 'Credit') THEN 'YES' ELSE 'NO' END AS HasCredit,
    CASE WHEN EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AP_Invoices' AND COLUMN_NAME = 'Balance') THEN 'YES' ELSE 'NO' END AS HasBalance,
    CASE WHEN EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'AP_Invoices' AND COLUMN_NAME = 'InvoiceID') THEN 'YES' ELSE 'NO' END AS HasInvoiceID;
