-- Check what columns exist in POS_CustomOrders table

SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE,
    COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'POS_CustomOrders'
ORDER BY ORDINAL_POSITION;
