-- Check JournalHeaders table structure

SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE,
    COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'JournalHeaders'
ORDER BY ORDINAL_POSITION;
