-- Check actual columns in InternalOrderHeader table
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    IS_NULLABLE,
    CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'InternalOrderHeader'
ORDER BY ORDINAL_POSITION;
