-- Check SupplierInvoices columns
SELECT 'SupplierInvoices' AS TableName, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'SupplierInvoices'
ORDER BY ORDINAL_POSITION

-- Check SupplierPayments columns
SELECT 'SupplierPayments' AS TableName, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'SupplierPayments'
ORDER BY ORDINAL_POSITION
